### ISSUE TITLE
Pull in master from holiday extras?

### ISSUE THREAD

**Issue by derekwsgray** [jagql/store-sequelize#10]
Hi - my company (unchartedsoftware) got a PR pulled into holidayextra's master branch (though a new release hasn't been made). Thinking of switching to your forks, but I'd need that change too. 

Thanks!

**Comment by championswimmer** [comment]
Sure will do that !

**Comment by derekwsgray** [comment]
Thanks!

**Comment by championswimmer** [comment]
@derekwsgray you mean this right https://github.com/holidayextras/jsonapi-store-relationaldb/pull/98

**Comment by derekwsgray** [comment]
Yes, that's the one. Thanks

**Comment by championswimmer** [comment]
done in v5.6.9
