### ISSUE TITLE
SELECT "meta" FROM "my_table" AS "my_table"

### ISSUE THREAD

**Issue by akdj** [jagql/store-sequelize#44]
Hi, 

I am working with a postgreSQL database,  I simply tried a Get request on 0.0.0.0/my_table and I get 

```
sequelize:pool connection acquired +3s
  sequelize:sql:pg executing(default) : SELECT count(*) AS "count" FROM "my_table" AS "my_table"; +3s
  sequelize:sql:pg executed(default) : SELECT count(*) AS "count" FROM "my_table" AS "my_table"; +2ms
  sequelize:pool connection released +2ms
  sequelize:pool connection acquired +2ms
  sequelize:sql:pg executing(default) : SELECT "id", "meta", "name", "mobilenumber" FROM "my_table" AS "my_table"; +2ms
  sequelize:pool connection released +2ms
  sequelize:pool connection drain due to process exit +3s
  sequelize:pool connection destroy +1ms
...
...
  jagql:requestCounter 0 GET /my_table +0ms
  jagql:validation:input {"type":"my_table"} +0ms
  jagql:handler:search {"type":"my_table","page":{"offset":0,"limit":50}} [{"status":"500","code":"EUNKNOWN","title":"An unknown error has occured","detail":"Something broke when connecting to the database - column \"meta\" does not exist"},null,null] +0ms
  jagql:errors GET /my_table {"status":"500","code":"EUNKNOWN","title":"An unknown error has occured","detail":"Something broke when connecting to the database - column \"meta\" does not exist"} +0ms
```

However there is no "meta" column in my_table. 

ps: Before to use jagql, I tested jsonapi-server and it jsonapi-store-relationaldb,  with them, I have "type" and "meta" issues...  with jagql, only "meta" issue. so I guess it is not a sequelize's node module's issue

**Comment by akdj** [comment]
My postgreSQL DB is a docker image, my database is created directly when I start the docker image as container, with option ``` -e   POSTGRES_DB: "my_db"   ```   

Then tables of my_db are created with sequelize's functions (sync, define, queryInterface)

**Comment by akdj** [comment]
- should I create database with sequelize, instead of by default with docker opt? 
- should I create tables manually? or with others ORM? 
- should I create intentionally "metat" column? 
- should I just remove the block of code about "meta" in the default.js in modelGenerators of the project ? (yes, I already tried, and it fixs my issue about "column \"meta\" does not exist" however, I don't know if it is a good way to do.) 

Very sorry, I asked too much because I have a lot tasks to do for these days, so I prefer to ask a lot to be quick on my side.

**Comment by championswimmer** [comment]
Create the tables using the `populate()` function
That will solve all your problems

**Comment by akdj** [comment]
what you mean by the function populate()?  in fact I didn't find this function or class in Sequelize node module

**Comment by akdj** [comment]
@championswimmer 

finally found out what you mean by "populate" function,    however, I get: 

```
TypeError: Cannot read property 'sync' of undefined
    at /works/my_server/node_modules/@jagql/store-sequelize/lib/sqlHandler.js:107:22
    at /works/my_server/node_modules/async/dist/async.js:3880:24
    at replenish (/works/my_server/node_modules/async/dist/async.js:1011:17)
    at /works/my_server/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/works/my_server/node_modules/async/dist/async.js:1041:24)
    at /works/my_server/node_modules/async/dist/async.js:1046:16
    at _parallel (/works/my_server/node_modules/async/dist/async.js:3879:5)
    at Object.series (/works/my_server/node_modules/async/dist/async.js:4735:5)
    at SqlStore.populate (/works/my_server/node_modules/@jagql/store-sequelize/lib/sqlHandler.js:123:9)
    at new JsonApiServer (/works/my_server/src/server/jsonapi.js:67:44)

```

Besides, I don't want to create my tables with my nodejs application.  In fact, the tables should be created with another nodejs application previously.

**Comment by akdj** [comment]
found out the issue, the .populate(); function  can only be called after the jsonapi.start(); 

But it doesn't resolve my issue about "meta" and "type" that I didn't create before, and that i don't want them be created at all.

**Comment by akdj** [comment]
I have no idea of why it have to have a "meta" column in all my tables for Json APi.
Could you tell me why it has to keep these columns ("type", and "meta")  ?  

Thank you  @championswimmer

**Comment by justinr1234** [comment]
@championswimmer I have an existing database that I won't be able to create with sequelize. What do I do?

**Comment by si-hyeon-ee** [comment]
delete this.meta part at lib/modelGenerators/default.js thus it solved.
